// next.config.mjs
import { createRequire } from 'module';

const require = createRequire(import.meta.url);

/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  images: {
    unoptimized: true,
    remotePatterns: [
      {
        protocol: 'https',
        hostname: 'images.archaeolist.com',
        port: '',
        pathname: '/**',
      },
      {
        protocol: 'https',
        hostname: 'merakivatravel.com',
        port: '',
        pathname: '/wp-content/uploads/**',
      },
    ],
  },
  async redirects() {
    return [
      // 208 individual site redirects
      { source: '/sites/aleppo-governorate/umm-el-marra', destination: '/sites/syria/umm-el-marra', permanent: true },
      { source: '/sites/amazonas-region/carachupa', destination: '/sites/peru/carachupa', permanent: true },
      { source: '/sites/amazonas-region/cochabamba-archaeological-site', destination: '/sites/peru/cochabamba-archaeological-site', permanent: true },
      { source: '/sites/amazonas-region/gran-saposoa', destination: '/sites/peru/gran-saposoa', permanent: true },
      { source: '/sites/amazonas-region/gran-vilaya', destination: '/sites/peru/gran-vilaya', permanent: true },
      { source: '/sites/amazonas-region/kuelap', destination: '/sites/peru/kuelap', permanent: true },
      { source: '/sites/amazonas-region/laguna-de-las-momias', destination: '/sites/peru/laguna-de-las-momias', permanent: true },
      { source: '/sites/amazonas-region/llactan', destination: '/sites/peru/llactan', permanent: true },
      { source: '/sites/amazonas-region/machu-pirqa', destination: '/sites/peru/machu-pirqa', permanent: true },
      { source: '/sites/amazonas-region/purunllacta-cheto', destination: '/sites/peru/purunllacta-cheto', permanent: true },
      { source: '/sites/amazonas-region/purunllacta-soloco', destination: '/sites/peru/purunllacta-soloco', permanent: true },
      { source: '/sites/amazonas-region/revash', destination: '/sites/peru/revash', permanent: true },
      { source: '/sites/amazonas-region/sarcophagi-of-carajia', destination: '/sites/peru/sarcophagi-of-carajia', permanent: true },
      { source: '/sites/amazonas-region/wilca', destination: '/sites/peru/wilca', permanent: true },
      { source: '/sites/ancash-region/casmasechin-culture', destination: '/sites/peru/casmasechin-culture', permanent: true },
      { source: '/sites/ancash-region/cerro-sechin', destination: '/sites/peru/cerro-sechin', permanent: true },
      { source: '/sites/ancash-region/chanquillo', destination: '/sites/peru/chanquillo', permanent: true },
      { source: '/sites/ancash-region/chavin-de-huantar', destination: '/sites/peru/chavin-de-huantar', permanent: true },
      { source: '/sites/ancash-region/el-castillo-de-huarmey', destination: '/sites/peru/el-castillo-de-huarmey', permanent: true },
      { source: '/sites/ancash-region/guitarrero-cave', destination: '/sites/peru/guitarrero-cave', permanent: true },
      { source: '/sites/ancash-region/honcopampa', destination: '/sites/peru/honcopampa', permanent: true },
      { source: '/sites/ancash-region/huacramarca', destination: '/sites/peru/huacramarca', permanent: true },
      { source: '/sites/ancash-region/intipanawin', destination: '/sites/peru/intipanawin', permanent: true },
      { source: '/sites/ancash-region/las-haldas', destination: '/sites/peru/las-haldas', permanent: true },
      { source: '/sites/ancash-region/maray-qalla', destination: '/sites/peru/maray-qalla', permanent: true },
      { source: '/sites/ancash-region/markahirka', destination: '/sites/peru/markahirka', permanent: true },
      { source: '/sites/ancash-region/mojeque', destination: '/sites/peru/mojeque', permanent: true },
      { source: '/sites/ancash-region/panamarca', destination: '/sites/peru/panamarca', permanent: true },
      { source: '/sites/ancash-region/tumshukayko', destination: '/sites/peru/tumshukayko', permanent: true },
      { source: '/sites/ancash-region/waraqayuq', destination: '/sites/peru/waraqayuq', permanent: true },
      { source: '/sites/ancash-region/wilcahuain', destination: '/sites/peru/wilcahuain', permanent: true },
      { source: '/sites/ancash-region/yanaque-quilcamarca', destination: '/sites/peru/yanaque-quilcamarca', permanent: true },
      { source: '/sites/ancash-region/yaynu', destination: '/sites/peru/yaynu', permanent: true },
      { source: '/sites/apurímac-region/inka-raqay-apurimac', destination: '/sites/peru/inka-raqay-apurimac', permanent: true },
      { source: '/sites/apurímac-region/muyu-muyu', destination: '/sites/peru/muyu-muyu', permanent: true },
      { source: '/sites/apurímac-region/sondor', destination: '/sites/peru/sondor', permanent: true },
      { source: '/sites/apurímac-region/usnu-muqu', destination: '/sites/peru/usnu-muqu', permanent: true },
      { source: '/sites/apurímac-region/yanaca', destination: '/sites/peru/yanaca', permanent: true },
      { source: '/sites/arequipa-region/huinao', destination: '/sites/peru/huinao', permanent: true },
      { source: '/sites/arequipa-region/marpa-peru', destination: '/sites/peru/marpa-peru', permanent: true },
      { source: '/sites/arequipa-region/mawkallaqta-castilla', destination: '/sites/peru/mawkallaqta-castilla', permanent: true },
      { source: '/sites/arequipa-region/paraccra-archaeological-site', destination: '/sites/peru/paraccra-archaeological-site', permanent: true },
      { source: '/sites/arequipa-region/toro-muerto', destination: '/sites/peru/toro-muerto', permanent: true },
      { source: '/sites/arequipa-region/uskallaqta', destination: '/sites/peru/uskallaqta', permanent: true },
      { source: '/sites/arequipa-region/uyu-uyu', destination: '/sites/peru/uyu-uyu', permanent: true },
      { source: '/sites/arusha-region/engaruka', destination: '/sites/tanzania/engaruka', permanent: true },
      { source: '/sites/arusha-region/olduvai-gorge', destination: '/sites/tanzania/olduvai-gorge', permanent: true },
      { source: '/sites/ayacucho-region/hatun-usnu', destination: '/sites/peru/hatun-usnu', permanent: true },
      { source: '/sites/ayacucho-region/huari-archaeological-site', destination: '/sites/peru/huari-archaeological-site', permanent: true },
      { source: '/sites/ayacucho-region/inka-raqay-ayacucho', destination: '/sites/peru/inka-raqay-ayacucho', permanent: true },
      { source: '/sites/ayacucho-region/inka-wasi-ayacucho', destination: '/sites/peru/inka-wasi-ayacucho', permanent: true },
      { source: '/sites/ayacucho-region/inti-watana-ayacucho', destination: '/sites/peru/inti-watana-ayacucho', permanent: true },
      { source: '/sites/ayacucho-region/kallapayuq-urqu', destination: '/sites/peru/kallapayuq-urqu', permanent: true },
      { source: '/sites/ayacucho-region/kanichi-peru', destination: '/sites/peru/kanichi-peru', permanent: true },
      { source: '/sites/ayacucho-region/millka', destination: '/sites/peru/millka', permanent: true },
      { source: '/sites/ayacucho-region/nawpallaqta-fajardo', destination: '/sites/peru/nawpallaqta-fajardo', permanent: true },
      { source: '/sites/ayacucho-region/nawpallaqta-lucanas', destination: '/sites/peru/nawpallaqta-lucanas', permanent: true },
      { source: '/sites/ayacucho-region/pikimachay', destination: '/sites/peru/pikimachay', permanent: true },
      { source: '/sites/ayacucho-region/pilluchu', destination: '/sites/peru/pilluchu', permanent: true },
      { source: '/sites/ayacucho-region/puka-urqu-ayacucho', destination: '/sites/peru/puka-urqu-ayacucho', permanent: true },
      { source: '/sites/ayacucho-region/pukara-victor-fajardo', destination: '/sites/peru/pukara-victor-fajardo', permanent: true },
      { source: '/sites/ayacucho-region/puntay-urqu', destination: '/sites/peru/puntay-urqu', permanent: true },
      { source: '/sites/ayacucho-region/qunchupata-ayacucho', destination: '/sites/peru/qunchupata-ayacucho', permanent: true },
      { source: '/sites/ayacucho-region/sara-sara', destination: '/sites/peru/sara-sara', permanent: true },
      { source: '/sites/ayacucho-region/tinyaq', destination: '/sites/peru/tinyaq', permanent: true },
      { source: '/sites/ayacucho-region/usnu-ayacucho', destination: '/sites/peru/usnu-ayacucho', permanent: true },
      { source: '/sites/ayacucho-region/usqunta', destination: '/sites/peru/usqunta', permanent: true },
      { source: '/sites/ayacucho-region/vilcashuaman', destination: '/sites/peru/vilcashuaman', permanent: true },
      { source: '/sites/ayacucho-region/wichqana', destination: '/sites/peru/wichqana', permanent: true },
      { source: '/sites/cajamarca-region/collor', destination: '/sites/peru/collor', permanent: true },
      { source: '/sites/cajamarca-region/condorcaga', destination: '/sites/peru/condorcaga', permanent: true },
      { source: '/sites/cajamarca-region/huayrapongo', destination: '/sites/peru/huayrapongo', permanent: true },
      { source: '/sites/cajamarca-region/ingatambo', destination: '/sites/peru/ingatambo', permanent: true },
      { source: '/sites/cajamarca-region/kuntur-wasi', destination: '/sites/peru/kuntur-wasi', permanent: true },
      { source: '/sites/cajamarca-region/pacopampa', destination: '/sites/peru/pacopampa', permanent: true },
      { source: '/sites/cajamarca-region/ventanillas-de-otuzco', destination: '/sites/peru/ventanillas-de-otuzco', permanent: true },
      { source: '/sites/callao-region/el-paraiso-peru', destination: '/sites/peru/el-paraiso-peru', permanent: true },
      { source: '/sites/campania/pompeii', destination: '/sites/italy/pompeii', permanent: true },
      { source: '/sites/cusco-region/chawaytiri', destination: '/sites/peru/chawaytiri', permanent: true },
      { source: '/sites/cusco-region/choquequirao', destination: '/sites/peru/choquequirao', permanent: true },
      { source: '/sites/cusco-region/choquequirao-puquio', destination: '/sites/peru/choquequirao-puquio', permanent: true },
      { source: '/sites/cusco-region/colcampata', destination: '/sites/peru/colcampata', permanent: true },
      { source: '/sites/cusco-region/coricancha', destination: '/sites/peru/coricancha', permanent: true },
      { source: '/sites/cusco-region/huamanmarca-la-convencion', destination: '/sites/peru/huamanmarca-la-convencion', permanent: true },
      { source: '/sites/cusco-region/huayna-picchu', destination: '/sites/peru/huayna-picchu', permanent: true },
      { source: '/sites/cusco-region/huchuy-qosqo', destination: '/sites/peru/huchuy-qosqo', permanent: true },
      { source: '/sites/cusco-region/inca-complex-at-pisac', destination: '/sites/peru/inca-complex-at-pisac', permanent: true },
      { source: '/sites/cusco-region/inca-trail-to-machu-picchu', destination: '/sites/peru/inca-trail-to-machu-picchu', permanent: true },
      { source: '/sites/cusco-region/inkilltambo', destination: '/sites/peru/inkilltambo', permanent: true },
      { source: '/sites/cusco-region/inti-punku', destination: '/sites/peru/inti-punku', permanent: true },
      { source: '/sites/cusco-region/inti-watana-calca', destination: '/sites/peru/inti-watana-calca', permanent: true },
      { source: '/sites/cusco-region/intihuatana-urubamba', destination: '/sites/peru/intihuatana-urubamba', permanent: true },
      { source: '/sites/cusco-region/kanamarka', destination: '/sites/peru/kanamarka', permanent: true },
      { source: '/sites/cusco-region/killarumiyuq', destination: '/sites/peru/killarumiyuq', permanent: true },
      { source: '/sites/cusco-region/llaqtapata', destination: '/sites/peru/llaqtapata', permanent: true },
      { source: '/sites/cusco-region/machu-colca', destination: '/sites/peru/machu-colca', permanent: true },
      { source: '/sites/cusco-region/machu-picchu', destination: '/sites/peru/machu-picchu', permanent: true },
      { source: '/sites/cusco-region/machu-pitumarka', destination: '/sites/peru/machu-pitumarka', permanent: true },
      { source: '/sites/cusco-region/machu-qinti', destination: '/sites/peru/machu-qinti', permanent: true },
      { source: '/sites/cusco-region/mawkallaqta-espinar', destination: '/sites/peru/mawkallaqta-espinar', permanent: true },
      { source: '/sites/cusco-region/mawkallaqta-paruro', destination: '/sites/peru/mawkallaqta-paruro', permanent: true },
      { source: '/sites/cusco-region/moray-inca-ruin', destination: '/sites/peru/moray-inca-ruin', permanent: true },
      { source: '/sites/cusco-region/mullu-qawa', destination: '/sites/peru/mullu-qawa', permanent: true },
      { source: '/sites/cusco-region/muyu-urqu', destination: '/sites/peru/muyu-urqu', permanent: true },
      { source: '/sites/cusco-region/muyuq-marka', destination: '/sites/peru/muyuq-marka', permanent: true },
      { source: '/sites/cusco-region/ninamarca', destination: '/sites/peru/ninamarca', permanent: true },
      { source: '/sites/cusco-region/nusta-hispana', destination: '/sites/peru/nusta-hispana', permanent: true },
      { source: '/sites/cusco-region/ollantaytambo', destination: '/sites/peru/ollantaytambo', permanent: true },
      { source: '/sites/cusco-region/pachatusan', destination: '/sites/peru/pachatusan', permanent: true },
      { source: '/sites/cusco-region/patallacta', destination: '/sites/peru/patallacta', permanent: true },
      { source: '/sites/cusco-region/pikillaqta', destination: '/sites/peru/pikillaqta', permanent: true },
      { source: '/sites/cusco-region/pinkuylluna', destination: '/sites/peru/pinkuylluna', permanent: true },
      { source: '/sites/cusco-region/puka-pukara', destination: '/sites/peru/puka-pukara', permanent: true },
      { source: '/sites/cusco-region/pumamarka-urubamba', destination: '/sites/peru/pumamarka-urubamba', permanent: true },
      { source: '/sites/cusco-region/pumawasi-anta', destination: '/sites/peru/pumawasi-anta', permanent: true },
      { source: '/sites/cusco-region/puyupatamarca', destination: '/sites/peru/puyupatamarca', permanent: true },
      { source: '/sites/cusco-region/qenko', destination: '/sites/peru/qenko', permanent: true },
      { source: '/sites/cusco-region/qollmay', destination: '/sites/peru/qollmay', permanent: true },
      { source: '/sites/cusco-region/quispiguanca', destination: '/sites/peru/quispiguanca', permanent: true },
      { source: '/sites/cusco-region/raqchi', destination: '/sites/peru/raqchi', permanent: true },
      { source: '/sites/cusco-region/rumicolca', destination: '/sites/peru/rumicolca', permanent: true },
      { source: '/sites/cusco-region/rumiwasi', destination: '/sites/peru/rumiwasi', permanent: true },
      { source: '/sites/cusco-region/runkuraqay', destination: '/sites/peru/runkuraqay', permanent: true },
      { source: '/sites/cusco-region/sacred-valley', destination: '/sites/peru/sacred-valley', permanent: true },
      { source: '/sites/cusco-region/sacsayhuaman', destination: '/sites/peru/sacsayhuaman', permanent: true },
      { source: '/sites/cusco-region/sayacmarca', destination: '/sites/peru/sayacmarca', permanent: true },
      { source: '/sites/cusco-region/tambomachay', destination: '/sites/peru/tambomachay', permanent: true },
      { source: '/sites/cusco-region/taqrachullu', destination: '/sites/peru/taqrachullu', permanent: true },
      { source: '/sites/cusco-region/tarahuasi', destination: '/sites/peru/tarahuasi', permanent: true },
      { source: '/sites/cusco-region/temple-of-the-moon-peru', destination: '/sites/peru/temple-of-the-moon-peru', permanent: true },
      { source: '/sites/cusco-region/tipon', destination: '/sites/peru/tipon', permanent: true },
      { source: '/sites/cusco-region/twelve-angled-stone', destination: '/sites/peru/twelve-angled-stone', permanent: true },
      { source: '/sites/cusco-region/vitcos', destination: '/sites/peru/vitcos', permanent: true },
      { source: '/sites/cusco-region/wanakawri-cusco', destination: '/sites/peru/wanakawri-cusco', permanent: true },
      { source: '/sites/cusco-region/waqrapukara', destination: '/sites/peru/waqrapukara', permanent: true },
      { source: '/sites/cusco-region/wata-cusco', destination: '/sites/peru/wata-cusco', permanent: true },
      { source: '/sites/cusco-region/wayna-qinti', destination: '/sites/peru/wayna-qinti', permanent: true },
      { source: '/sites/cusco-region/wayna-tawqaray', destination: '/sites/peru/wayna-tawqaray', permanent: true },
      { source: '/sites/cusco-region/winay-wayna', destination: '/sites/peru/winay-wayna', permanent: true },
      { source: '/sites/cusco-region/wiraqucha-cusco', destination: '/sites/peru/wiraqucha-cusco', permanent: true },
      { source: '/sites/huancavelica-region/inka-machay-peru', destination: '/sites/peru/inka-machay-peru', permanent: true },
      { source: '/sites/huancavelica-region/inka-wasi-huancavelica', destination: '/sites/peru/inka-wasi-huancavelica', permanent: true },
      { source: '/sites/huancavelica-region/uchkus-inkanan', destination: '/sites/peru/uchkus-inkanan', permanent: true },
      { source: '/sites/huancavelica-region/wiraqucha-pirqa', destination: '/sites/peru/wiraqucha-pirqa', permanent: true },
      { source: '/sites/huánuco-region/hatun-machay', destination: '/sites/peru/hatun-machay', permanent: true },
      { source: '/sites/huánuco-region/hatun-uchku', destination: '/sites/peru/hatun-uchku', permanent: true },
      { source: '/sites/huánuco-region/hualpayunca', destination: '/sites/peru/hualpayunca', permanent: true },
      { source: '/sites/huánuco-region/huanuco-pampa', destination: '/sites/peru/huanuco-pampa', permanent: true },
      { source: '/sites/huánuco-region/isog', destination: '/sites/peru/isog', permanent: true },
      { source: '/sites/huánuco-region/kotosh', destination: '/sites/peru/kotosh', permanent: true },
      { source: '/sites/huánuco-region/miyu-pampa', destination: '/sites/peru/miyu-pampa', permanent: true },
      { source: '/sites/huánuco-region/pumaq-hirka', destination: '/sites/peru/pumaq-hirka', permanent: true },
      { source: '/sites/huánuco-region/quillarumi', destination: '/sites/peru/quillarumi', permanent: true },
      { source: '/sites/huánuco-region/quillcay-machay', destination: '/sites/peru/quillcay-machay', permanent: true },
      { source: '/sites/huánuco-region/susupillo', destination: '/sites/peru/susupillo', permanent: true },
      { source: '/sites/huánuco-region/takaq', destination: '/sites/peru/takaq', permanent: true },
      { source: '/sites/huánuco-region/tikra', destination: '/sites/peru/tikra', permanent: true },
      { source: '/sites/huánuco-region/urpish', destination: '/sites/peru/urpish', permanent: true },
      { source: '/sites/huánuco-region/usnu-huanuco', destination: '/sites/peru/usnu-huanuco', permanent: true },
      { source: '/sites/ica-region/cantalloc-aqueducts', destination: '/sites/peru/cantalloc-aqueducts', permanent: true },
      { source: '/sites/ica-region/huayuri', destination: '/sites/peru/huayuri', permanent: true },
      { source: '/sites/ica-region/la-centinela', destination: '/sites/peru/la-centinela', permanent: true },
      { source: '/sites/ica-region/paracas-candelabra', destination: '/sites/peru/paracas-candelabra', permanent: true },
      { source: '/sites/ica-region/pernil-alto', destination: '/sites/peru/pernil-alto', permanent: true },
      { source: '/sites/ica-region/puquios', destination: '/sites/peru/puquios', permanent: true },
      { source: '/sites/ica-region/tambo-colorado', destination: '/sites/peru/tambo-colorado', permanent: true },
      { source: '/sites/jersey/grouville-hoard', destination: '/sites/united-kingdom/grouville-hoard', permanent: true },
      { source: '/sites/jersey/haut-de-la-garenne', destination: '/sites/united-kingdom/haut-de-la-garenne', permanent: true },
      { source: '/sites/jersey/la-cotte-de-st-brelade', destination: '/sites/united-kingdom/la-cotte-de-st-brelade', permanent: true },
      { source: '/sites/jersey/la-motte-jersey', destination: '/sites/united-kingdom/la-motte-jersey', permanent: true },
      { source: '/sites/jersey/le-couperon-dolmen', destination: '/sites/united-kingdom/le-couperon-dolmen', permanent: true },
      { source: '/sites/jersey/le-pinacle', destination: '/sites/united-kingdom/le-pinacle', permanent: true },
      { source: '/sites/jersey/les-landes', destination: '/sites/united-kingdom/les-landes', permanent: true },
      { source: '/sites/jersey/trinity-hoard', destination: '/sites/united-kingdom/trinity-hoard', permanent: true },
      { source: '/sites/jersey/ville-es-nouaux', destination: '/sites/united-kingdom/ville-es-nouaux', permanent: true },
      { source: '/sites/junín-region/chacamarca-historic-sanctuary', destination: '/sites/peru/chacamarca-historic-sanctuary', permanent: true },
      { source: '/sites/junín-region/quri-winchus', destination: '/sites/peru/quri-winchus', permanent: true },
      { source: '/sites/junín-region/tarmatambo', destination: '/sites/peru/tarmatambo', permanent: true },
      { source: '/sites/junín-region/wari-willka', destination: '/sites/peru/wari-willka', permanent: true },
      { source: '/sites/la-libertad-region/caballo-muerto', destination: '/sites/peru/caballo-muerto', permanent: true },
      { source: '/sites/la-libertad-region/el-brujo', destination: '/sites/peru/el-brujo', permanent: true },
      { source: '/sites/la-libertad-region/gran-pajaten', destination: '/sites/peru/gran-pajaten', permanent: true },
      { source: '/sites/la-libertad-region/huaca-prieta', destination: '/sites/peru/huaca-prieta', permanent: true },
      { source: '/sites/la-libertad-region/marcahuamachuco', destination: '/sites/peru/marcahuamachuco', permanent: true },
      { source: '/sites/la-libertad-region/pacatnamu', destination: '/sites/peru/pacatnamu', permanent: true },
      { source: '/sites/la-libertad-region/pirca-pirca-la-libertad', destination: '/sites/peru/pirca-pirca-la-libertad', permanent: true },
      { source: '/sites/la-libertad-region/san-jose-de-moro', destination: '/sites/peru/san-jose-de-moro', permanent: true },
      { source: '/sites/lambayeque-region/batan-grande', destination: '/sites/peru/batan-grande', permanent: true },
      { source: '/sites/lambayeque-region/cerro-patapo-ruins', destination: '/sites/peru/cerro-patapo-ruins', permanent: true },
      { source: '/sites/lambayeque-region/chotuna-chornancap', destination: '/sites/peru/chotuna-chornancap', permanent: true },
      { source: '/sites/lambayeque-region/tucume', destination: '/sites/peru/tucume', permanent: true },
      { source: '/sites/lima-region/buena-vista-peru', destination: '/sites/peru/buena-vista-peru', permanent: true },
      { source: '/sites/lima-region/caral', destination: '/sites/peru/caral', permanent: true },
      { source: '/sites/lima-region/huaca-pucllana', destination: '/sites/peru/huaca-pucllana', permanent: true },
      { source: '/sites/lima-region/huaycan-de-pariachi', destination: '/sites/peru/huaycan-de-pariachi', permanent: true },
      { source: '/sites/lima-region/incahuasi-lima', destination: '/sites/peru/incahuasi-lima', permanent: true },
      { source: '/sites/lima-region/pirca-pirca-lima', destination: '/sites/peru/pirca-pirca-lima', permanent: true },
      { source: '/sites/lima-region/puruchuco', destination: '/sites/peru/puruchuco', permanent: true },
      { source: '/sites/lima-region/wamanmarka-lima', destination: '/sites/peru/wamanmarka-lima', permanent: true },
      { source: '/sites/madre-de-dios-region/pusharo', destination: '/sites/peru/pusharo', permanent: true },
      { source: '/sites/pasco-region/guellayhuasin', destination: '/sites/peru/guellayhuasin', permanent: true },
      { source: '/sites/pasco-region/kuntuyuq', destination: '/sites/peru/kuntuyuq', permanent: true },
      { source: '/sites/pasco-region/markapukyu', destination: '/sites/peru/markapukyu', permanent: true },
      { source: '/sites/pasco-region/qaqapatan', destination: '/sites/peru/qaqapatan', permanent: true },
      { source: '/sites/pasco-region/warawtampu', destination: '/sites/peru/warawtampu', permanent: true },
      { source: '/sites/pasco-region/yuraq-machay', destination: '/sites/peru/yuraq-machay', permanent: true },
      { source: '/sites/raqqa-governorate/al-jarud', destination: '/sites/syria/al-jarud', permanent: true },
      { source: '/sites/southeastern-anatolia/hirbemerdon-tepe', destination: '/sites/turkey/hirbemerdon-tepe', permanent: true },

      // 23 old country page redirects (unique old_country_slug -> new_country_slug)
      { source: '/sites/aleppo-governorate', destination: '/sites/syria', permanent: true },
      { source: '/sites/amazonas-region', destination: '/sites/peru', permanent: true },
      { source: '/sites/ancash-region', destination: '/sites/peru', permanent: true },
      { source: '/sites/apurímac-region', destination: '/sites/peru', permanent: true },
      { source: '/sites/arequipa-region', destination: '/sites/peru', permanent: true },
      { source: '/sites/arusha-region', destination: '/sites/tanzania', permanent: true },
      { source: '/sites/ayacucho-region', destination: '/sites/peru', permanent: true },
      { source: '/sites/cajamarca-region', destination: '/sites/peru', permanent: true },
      { source: '/sites/callao-region', destination: '/sites/peru', permanent: true },
      { source: '/sites/campania', destination: '/sites/italy', permanent: true },
      { source: '/sites/cusco-region', destination: '/sites/peru', permanent: true },
      { source: '/sites/huancavelica-region', destination: '/sites/peru', permanent: true },
      { source: '/sites/huánuco-region', destination: '/sites/peru', permanent: true },
      { source: '/sites/ica-region', destination: '/sites/peru', permanent: true },
      { source: '/sites/jersey', destination: '/sites/united-kingdom', permanent: true },
      { source: '/sites/junín-region', destination: '/sites/peru', permanent: true },
      { source: '/sites/la-libertad-region', destination: '/sites/peru', permanent: true },
      { source: '/sites/lambayeque-region', destination: '/sites/peru', permanent: true },
      { source: '/sites/lima-region', destination: '/sites/peru', permanent: true },
      { source: '/sites/madre-de-dios-region', destination: '/sites/peru', permanent: true },
      { source: '/sites/pasco-region', destination: '/sites/peru', permanent: true },
      { source: '/sites/raqqa-governorate', destination: '/sites/syria', permanent: true },
      { source: '/sites/southeastern-anatolia', destination: '/sites/turkey', permanent: true },
    ];
  },
};

export default nextConfig;
